apiVersion: batch/v1
kind: Job
metadata:
  generateName: nginx-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - aaaaaname: nginx
        image: nginx:latest
        command:
          - "echo"
          - "hello"
      restartPolicy: OnFailure
  backoffLimit: 1
