Mappings:
  EnvMap:
    devstg:
      Env3: devstg-env3
      Env4: devstg-env4
    devstg2:
      Env3: devstg2-env3
      Env4: devstg2-env4

Parameters:
  EnvName:
    Default: devstg
    Type: String
    AllowedValues: [devstg, devstg2]

Conditions:
  CreateDevstgResources: !Equals [!Ref EnvName, devstg]
  CreateDevstg2Resources: !Equals [!Ref EnvName, devstg2]


Resources:
# ------------------------------------------------------------#
# Secrets Manager
# ------------------------------------------------------------#
  EnvVar:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub test/env/${EnvName}
      SecretString: !Sub
      - |
        {
           "ENV1": "env1",
           "ENV2": "env2",
           "ENV3": "${Env3}",
           "ENV4": "${Env4}"
        }
      - Env3: !If [CreateDevstgResources, !FindInMap [EnvMap, !Ref EnvName, Env3], !If [CreateDevstg2Resources, !FindInMap [EnvMap, !Ref EnvName, Env3], test]]
        Env4: !If [CreateDevstgResources, !FindInMap [EnvMap, !Ref EnvName, Env4], !If [CreateDevstg2Resources, !FindInMap [EnvMap, !Ref EnvName, Env4], test]]

