name: 'Check deployment conditions'
description: 'Check deployment conditions'
inputs:
  ref_name:
    required: true
  env_name:
    required: true
  bucket:
    default: s3://nh2024-test-results/${{ github.event.repository.name }}
    required: false  

outputs:
  deployment_flg:
    description: 'Flag whether to deploy or not'
    value: ${{ steps.check-deploy.outputs.deployment_flg }}

runs:
  using: "composite"
  steps:
  - id: check-deploy
    run: |
      echo ${{ inputs.bucket }}
      if [[ "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]] || \
  
         # Execute if it's a develop branch and the environment is either dev1 or integration.
         [[ ( "${{ inputs.ref_name }}" == develop && \
            ( "${{ inputs.env_name }}" == "dev1" || "${{ inputs.env_name }}" == "integration" )) ]] || \
      
         # Execute if it's a release or hotfix branch, but not for the dev1 or integration environments.
         [[ (( "${{ inputs.ref_name }}" = release/* || "${{ inputs.ref_name }}" = hotfix/* ) && \
               "${{ inputs.env_name }}" != "dev1" && "${{ inputs.env_name }}" != "integration") ]]; then
  
        echo "deployment_flg=true" >> $GITHUB_OUTPUT
      else
        echo "deployment_flg=false" >> $GITHUB_OUTPUT
      fi
    shell: bash
