name: Check manifest

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: instrumenta/conftest-action@master
      with:
        files: template/manifest
    - name: check policy
      run: |
        ls
        cat policy
