name: Run docker image

on:
  workflow_dispatch:

jobs:
  run-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check USER
        run: |
          echo $(id -u $USER)
          echo $(id -g $USER)
