name: Run docker image

on:
  workflow_dispatch:

jobs:
  run-docker-image:
    runs-on: ubuntu-latest
    outputs:
      user_id: ${{ steps.step1.outputs.USER_ID }}
      group_id: ${{ steps.step1.outputs.USER_GROUP }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: step1
        run: |
          echo "USER_ID=$(id -u $USER)" >> $GITHUB_OUTPUT
          echo "USER_GROUP=$(id -g $USER)" >> $GITHUB_OUTPUT

      - id: step2
        run: |
          echo ${{ env.USER_ID }}
          echo ${{ env.USER_GROUP }}

  test-job:
    runs-on: ubuntu-latest
    needs: run-docker-image
    steps:
      - id: step1
        run: |
          ls
          pwd
          echo ${{needs.run-docker-image.outputs.user_id}} 
          echo ${{needs.run-docker-image.outputs.group_id}}

