name: Run docker image

on:
  workflow_dispatch:

jobs:
  set-env:
    runs-on: ubuntu-latest
    outputs:
      user_id: ${{ steps.step1.outputs.USER_ID }}
      group_id: ${{ steps.step1.outputs.USER_GROUP }}
    steps:
    - run: |
        echo "USER_ID=$(id -u $USER)" >> $GITHUB_OUTPUT
        echo "USER_GROUP=$(id -g $USER)" >> $GITHUB_OUTPUT


  run-docker-image:
    runs-on: ubuntu-latest
    needs: set-env
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up python 3.9
      uses: addnab/docker-run-action@v3
      env:
        PACKAGE_DIR: /work/python-packages
        USER_ID: ${{needs.run-docker-image.outputs.user_id}}
        GROUP_ID: ${{needs.run-docker-image.outputs.group_id}}
      with:
        image: python:3.9-slim-buster
        # Mount dir to /work in container and reflect user info in build environment to container
        options: -v ${{ github.workspace }}:/work -v /etc/group:/etc/group:ro -v /etc/passwd:/etc/passwd:ro -u ${{ env.USER_ID }}:${{ env.GROUP_ID}}
        run: |
          mkdir ${{ env.PACKAGE_DIR }}
          pip install boto3 -t ${{ env.PACKAGE_DIR }}
          ls ${{ env.PACKAGE_DIR }}