name: Check manifest

on:
  workflow_dispatch:

jobs:
  kubeconform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker://ghcr.io/yannh/kubeconform:master
        with:
          #entrypoint: '/kubeconform'
          #args: "-summary -schema-location default -schema-location \"schemas/{{ .ResourceKind }}_{{ .ResourceAPIVersion }}.json\" -output json template/kubeconform-test"

          entrypoint: ['sh', '-c']
          args: [
          "/kubeconform -summary -schema-location default -schema-location \"schemas/{{ .ResourceKind }}_{{ .ResourceAPIVersion }}.json\" -output json template/kubeconform-test"
          ]
