name: Check manifest

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  kubeconform:
    runs-on: ubuntu-latest
    steps:
      - name: login to Github Packages
        run: echo "${{ github.token }}" | docker login https://ghcr.io -u ${GITHUB_ACTOR} --password-stdin
      - uses: actions/checkout@v2
      - uses: docker://ghcr.io/yannh/kubeconform:master
        with:
          entrypoint: '/kubeconform'
          args: "-summary -schema-location default -schema-location \"schemas/{{ .ResourceKind }}_{{ .ResourceAPIVersion }}.json\" -output json template/manifest"
#          args: "-summary -schema-location default \
#                 -schema-location schemas/rollout_v1alpha1.json \
#                 -schema-location schemas/externalsecret_v1.json \
#                 -schema-location schemas/targetgroupbinding_v1alpha1.json \
#                 -schema-location schemas/targetgroupbinding_v1beta1.json \
#                 -output json \
#                 template/manifest/external-secret.yaml"
