name: Matrix test

on:
  workflow_dispatch:
    inputs:
      env_list:
        type: string
        required: true
        default: 'integration,uat,preprod,prod'

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.create-matrix.outputs.matrix }}
    steps:
      - id: create-matrix
        run: |
          env_list="${{ github.event.inputs.env_list }}"
          matrix_json="[\"${env_list//,/'","'}\"]"
          echo "matrix=${matrix_json}" >> $GITHUB_OUTPUT
          echo $matrix_json

  deploy:
    needs: set-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env: ${{fromJson(needs.set-matrix.outputs.matrix)}}
    steps:
      - run: echo ${{ matrix.env }}
      - name: Check deployment conditions
        id: check-conditions
        run: |
          if [[ (! "${{ github.ref_name }}" = release* && ! "${{ github.ref_name }}" = hotfix* && \
             ( "${{ matrix.env_name }}" == "dev1" || "${{ matrix.env_name }}" == "integration" )) || \
             (( "${{ github.ref_name }}" = release* || "${{ github.ref_name }}" = hotfix*) && \
             "${{ matrix.env_name }}" != "dev1" && "${{ matrix.env_name }}" != "integration") ]]; then
            echo "RELEASE_FLG=true" >> $GITHUB_ENV
          else
            echo "RELEASE_FLG=false" >> $GITHUB_ENV
          fi
      
      - name: Check environment variables
        if: env.RELEASE_FLG == 'true'
        run: |
          echo "Branch: ${{ env.BRANCH }}"
          echo "Manifest file path: ${{ env.MANIFEST_FILE_PATH }}"
  
