name: Matrix test

on:
  workflow_dispatch:

jobs:
  set-matrix:
    runs-on: ubuntu-latest

    outputs:
      list: ${{ steps.get_list.outputs.value }}

    steps:
    - name: step1
      id: get_list
      run: |
        echo '"${{ github.event.repository.name }}"' | jq -c
        list=$(echo '"${{ github.event.repository.name }}"' | jq -c)
        echo "value=${list}" >> $GITHUB_OUTPUT

  matrix-test:
    needs: set-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env_name: [uat, preprod]
        include:
        - manifest_file_path: ${{fromJson(needs.set-matrix.outputs.list)}}
        - branch: develop
        - branch: maint-test
          manifest_file_path: common/xxx/xxx.yaml
          env_name: preprod

    steps:
    - run: |
        echo ${{ matrix.env_name }} ${{ matrix.branch }} ${{ matrix.manifest_file_path}}
