name: Matrix test

on:
  workflow_dispatch:
    inputs:
      env_list:
        type: string
        required: true
        default: 'integration,uat,preprod,prod'

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.create-matrix.outputs.matrix }}
    steps:
      - id: create-matrix
        run: |
          env_list="${{ github.event.inputs.env_list }}"
          matrix_json="[\"${env_list//,/'","'}\"]"
          echo "matrix=${matrix_json}" >> $GITHUB_OUTPUT
          echo $matrix_json

  deploy:
    needs: set-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env: ${{fromJson(needs.set-matrix.outputs.matrix)}}
    steps:
      - run: echo ${{ matrix.env }}
      - name: Set environment specific variables
        run: |
          if [ "${{ matrix.env }}" == "dev1" ]; then
            echo "BRANCH=develop" >> $GITHUB_ENV
            echo "MANIFEST_FILE_PATH=overlay/dev1/customer/mercury-lambda-updater/${{ github.event.repository.name }}-updater/patch.yaml" >> $GITHUB_ENV
          elif [ "${{ matrix.env }}" == "integration" ]; then
            echo "BRANCH=develop" >> $GITHUB_ENV
            echo "MANIFEST_FILE_PATH=overlay/integration/customer/mercury-lambda-updater/${{ github.event.repository.name }}-updater/patch.yaml" >> $GITHUB_ENV
          fi
      - run: |
          echo "Branch: ${{ env.BRANCH }}"
          echo "Manifest file path: ${{ env.MANIFEST_FILE_PATH }}"
  
