name: Matrix test

on:
  workflow_dispatch:
    inputs:
      env_list:
        type: string
        required: true
        default: 'integration,uat,preprod,prod'

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.create-matrix.outputs.matrix }}
    steps:
      - id: create-matrix
        run: |
          env_list="${{ github.event.inputs.env_list }}"
          matrix_json="[{\"env_name\":\"${env_list//,/'},{\"env_name\":\"'}\"}]"
          echo "matrix=${matrix_json}" >> $GITHUB_OUTPUT

  deploy:
    needs: set-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.set-matrix.outputs.matrix)}}
    steps:
      - name: Deploy
        run: |
          echo "env_name ${{ matrix.env_name }}"
