name: Matrix test

on:
  push:
    branches:
    - 'release/**'
    - develop

  workflow_dispatch:
    inputs:
      env_list:
        type: string
        required: true
        default: 'integration,uat,preprod,prod'

  env:
    ENV: test

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.create-matrix.outputs.matrix }}
    steps:
      - id: create-matrix
        run: |
          env_list="${{ github.event.inputs.env_list }}"
          matrix_json="[\"${env_list//,/'","'}\"]"
          echo "matrix=${matrix_json}" >> $GITHUB_OUTPUT
          echo $matrix_json

  env_test:
    needs: set-matrix    
    runs-on: ubuntu-latest
    steps:
      - id: env_test
        run: |
          echo ${{ env.ENV }}

  deploy:
    needs: set-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env_name: ${{fromJson(needs.set-matrix.outputs.matrix)}}
    steps:
    - name: Check deployment conditions
      uses: RyotaArai/sample/composite_actions/check_deploy@main
      with:
        ref_name: ${{ github.ref_name }}
        env_name: ${{ matrix.env_name }}

    - name: Set Deployment Flag
      run: echo "deployment_flg=${{ steps.deploy.outputs.deployment_flg }}" >> $GITHUB_ENV

    - name: Check environment variables
      if: env.deployment_flg == "true"
      run: |
        echo ${{ matrix.env_name }}
  
