name: Matrix test

on:
  workflow_dispatch:

jobs:
  matrix-test:
    needs: set-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env_name: [uat, preprod, prod]
        include:
        - manifest_file_path: ${{ github.event.repository.name }}
        - branch: develop

        - branch: maint-test
          manifest_file_path: common/xxx/xxx.yaml
          env_name: preprod

        - branch: prod-env
          manifest_file_path: common/xxx/xxx.yaml
          env_name: prod

    steps:
    - run: |
        echo ENV:${{ matrix.env_name }} BRANCH:${{ matrix.branch }} PATH:${{ matrix.manifest_file_path}}
