name: Matrix test

on:
  workflow_dispatch:
    inputs:
      env_list:
        type: string
        required: true
        default: 'integration,uat,preprod,prod'

jobs:
  set-env:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Set Matrix
        id: set-matrix
        run: |
          echo "::set-output name=matrix::{\"env_name\": [${{ github.event.inputs.env_list }}]}"

  matrix-test:
    needs: set-env
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.set-env.outputs.matrix)}}
    steps:
      - run: |
          echo env_name: ${{ matrix.env_name }}


