name: Update Secret Manager

on:
  push:
    paths-ignore:
    - '.github/**'
    branches:
    - main
  workflow_dispatch:

jobs:
  update_secret_manager:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        env:
          AWS_ACCOUNT_ID: ${{ secrets.DEV_AWS_ACCOUNT_ID }}
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::${{ secrets.DEV_AWS_ACCOUNT_ID }}:role/cfn_role
          role-session-name: MySession
      - run: aws sts get-caller-identity
